/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McqRouteImport } from './routes/mcq'
import { Route as IndexRouteImport } from './routes/index'

const McqRoute = McqRouteImport.update({
  id: '/mcq',
  path: '/mcq',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcq': typeof McqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcq': typeof McqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcq': typeof McqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mcq'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mcq'
  id: '__root__' | '/' | '/mcq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McqRoute: typeof McqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcq': {
      id: '/mcq'
      path: '/mcq'
      fullPath: '/mcq'
      preLoaderRoute: typeof McqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McqRoute: McqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
